<a href="https://colab.research.google.com/github/Pmskabir1234/Torch/blob/main/breast_cancer_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (2.0.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (2026.2.25)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [80]:
import pandas as pd
import numpy as np
import opendatasets as od
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch

In [69]:
od.download("https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset")

Skipping, found downloaded files in "./breast-cancer-dataset" (use force=True to force download)

In [90]:
df = pd.read_csv("/content/breast-cancer-dataset/breast-cancer.csv")

In [91]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [92]:
df.isna().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [93]:
df = df.drop(columns='id')

In [94]:
df.head(5)

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [76]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df['diagnosis'], test_size=0.2, shuffle=True)

In [95]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

type(X_test)

numpy.ndarray

In [96]:
le = LabelEncoder()
y_test = le.fit_transform(y_test)
y_train = le.fit_transform(y_train)

type(y_test)

numpy.ndarray

In [97]:
X_test = torch.from_numpy(X_test)
X_train = torch.from_numpy(X_train)
y_test = torch.from_numpy(y_test)
y_train = torch.from_numpy(y_train)

In [99]:
X_test.shape

torch.Size([114, 30])

In [103]:
lr = 0.1
Epochs = 25

In [115]:
class SimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, requires_grad=True, dtype=torch.float64)
    self.bias = torch.zeros(1, requires_grad=True, dtype=torch.float64)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_func(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    # Corrected binary cross-entropy loss
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [121]:
#model instance
model = SimpleNN(X_train)

for i in range(Epochs):
  y_pred = model.forward(X_train)
  loss = model.loss_func(y_pred, y_train)
  print(f"Epoch: {i+1}  Loss: {loss.item()}")

  loss.backward()
  with torch.no_grad():
    model.weights -= lr*model.weights.grad
    model.bias -= lr*model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()

Epoch: 1  Loss: 4.096423521592182
Epoch: 2  Loss: 3.7847894656830525
Epoch: 3  Loss: 3.4827926200757524
Epoch: 4  Loss: 3.196995810917979
Epoch: 5  Loss: 2.928226464508952
Epoch: 6  Loss: 2.6801636804640863
Epoch: 7  Loss: 2.4433847089979652
Epoch: 8  Loss: 2.2268870105655916
Epoch: 9  Loss: 2.0302556401711267
Epoch: 10  Loss: 1.8522122924168178
Epoch: 11  Loss: 1.6936317736072646
Epoch: 12  Loss: 1.5536509225740631
Epoch: 13  Loss: 1.430526759643275
Epoch: 14  Loss: 1.322648987855672
Epoch: 15  Loss: 1.228521907299929
Epoch: 16  Loss: 1.1467513818762425
Epoch: 17  Loss: 1.0760363520859493
Epoch: 18  Loss: 1.015164013295469
Epoch: 19  Loss: 0.9630075716933604
Epoch: 20  Loss: 0.9185254671224719
Epoch: 21  Loss: 0.880761086300536
Epoch: 22  Loss: 0.8488422254667951
Epoch: 23  Loss: 0.8219798324530377
Epoch: 24  Loss: 0.7994658079167247
Epoch: 25  Loss: 0.7806698387005488

In [123]:
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred = (y_pred > 0.5).float()

acc = (y_pred == y_test).float().mean()
print(acc.item())

0.5344721674919128

#Key Points

1. StandardScaler, LabelEncoder ***fit_transform*** returns a numpy array.
2. Here, no. of weights ▶ no. of features.
3. The typical dataflow to train a model ▪ Create a model ▶ Forward pass ▶ Prediction and Loss Calculation ▶ Update parameters ▶ Clear Gradients ▶ Repeat